### ISSUE TITLE
how to set FIRMWARE_DIR

### ISSUE THREAD

**Issue by 1163307648** [firmadyne/firmadyne#18]
# specify full path to FIRMADYNE repository
FIRMWARE_DIR=/home/cc/scraper/firmware/spiders/output/dlink/
#FIRMWARE_DIR=/home/cc/firmadyne/

# specify full paths to other directories 

BINARY_DIR=/home/cc/firmadyne/binaries/
TARBALL_DIR=/home/cc/firmadyne/images/
SCRATCH_DIR=/home/cc/firmadyne/scratch/
SCRIPT_DIR=/home/cc/firmadyne/scripts/

when I set FIRMWARE_DIR=/home/cc/firmadyne/,it can  extract the filesystem.But when i set FIRMWARE_DIR=/home/cc/scraper/firmware/spiders/output/dlink/,it failed to extract filesystem of the firmware in this directory。how should i do?

**Comment by ddcc** [comment]
That is expected behavior. You should set `FIRMWARE_DIR` to the full path of the root directory of this repository. Then, when you want to extract the firmware, just pass the correct path, e.g. from the directory `/home/cc/firmadyne/`, execute `./sources/extractor/extractor.py -b dlink -sql 127.0.0.1 -np -nk ../firmware/spiders/output/dlink/foo.bin`
