### ISSUE TITLE
MIPS kernel

### ISSUE THREAD

**Issue by prashast** [firmadyne/firmadyne#44]
Not really an issue, was just curious as to why you guys used this particular version of the kernel(v2.6.32.70) for emulating the firmwares. Is there some particular reason you guys didn't want to cross compile newer versions of the kernel?

**Comment by ddcc** [comment]
A lot of firmware used the 2.6.x kernel or older, so we started with that LTS branch for both ARM and MIPS, which I believe was 2.6.32.x.

For ARM, the target platform we were using at the time (one of realview-pb/versatilepb), didn't support ARMv6 or newer, so we ended up upgrading to a newer target platform (I believe vexpress-a9/vexpress-a15). This required a kernel update through a few LTS branches to 3.10.x, due to flaky support for platform peripherals and relevant stability patches not being backported to LTS. But then we realized that being unable to attach multiple networking devices to the emulated PCI bus (which was itself hard to find support for) was a problem, so we decided to use VirtIO instead of trying to finding a suitable target platform. Again, there were kernel problems with VirtIO support for ARM lagging behind x86, and ARM support being rewritten for ARMv8/AArch64, so we upgraded again and ended up at 4.1.x. At some point we also wanted kernel support for kretprobes, but I don't recall when that was done.
