### ISSUE TITLE
Debugging firmware images that aren't successfully emulated

### ISSUE THREAD

**Issue by prashast** [firmadyne/firmadyne#46]
Hey @ddcc , I had a question regarding the debugging framework for binaries that aren't successfully emulated. I wanted to remotely debug a web server binary that was running as a part of the emulation but I was having trouble connecting to the gdb stub that I was running in QEMU. Do you have any pointers on as to how you go about debugging these binaries?

**Comment by ddcc** [comment]
Unfortunately, debugging system-mode QEMU is a pain, so I try to avoid it, and substitute with workarounds when possible. There's a discussion of this in the comments for issue #28 : https://github.com/firmadyne/firmadyne/issues/28#issuecomment-266573357 , and in the next few comments.

Aside from using QEMU's built-in stubs for system/user-mode emulation, another approach is to use system-mode emulation, build a statically-linked GDB stub for the target, and run it inside the emulator attached to the binary of interest. Of course, you'll need a cross-compile toolchain, which can also be difficult to get ahold of; you can either build it from scratch using e.g. buildroot, or attempt to find GPL sources and look for a toolchain in there. Alternatively, if the platform is popular enough, you can usually find pre-compiled binaries online. Also, if you have access to IDA Pro, it comes with its own pre-compiled debug stubs (not GDB-compatible) in the install directory.

**Comment by prashast** [comment]
Yeah, I currently had a statically linked gdbserver binary which I had attached to a webserver binary but was having trouble connecting to the stub from the host using the tap/bridge interface. Either way, thanks for the prompt reply.

**Comment by prashast** [comment]
Hi, so I've been trying for a while to setup the debugging framework so that I can figure out where exactly is the web server binary crashing when I'm trying to emulate it and for that I had chosen to go the statically linked gdbserver route as I had mentioned before. However, I am having trouble connecting my host GDB to the gdb stub running on the emulated debian mipsel machine. 

I had setup the bridge and the tap interface like so:
```
sudo brctl addbr br0
# ip addr add 192.168.179.1/24 broadcast 192.168.179.255 dev br0
# ip link set br0 up
# ip tuntap add dev tap0 mode tap user $(whoami)
# ip link set tap0 up promisc on
 # ip link set tap0 master br0
 # dnsmasq --interface=br0 --bind-interfaces --dhcp-range=192.168.179.2,192.168.179.254
```

After which I ran the qemu using the tap interface that I had setup. My guest gets an ip address(192.168.179.89) in the range set by the dnsmasq and I am able to ping the guest from the host and vice versa and even able to ssh into the guest from the host. However when I setup a gdb session `./gdbserver --multi 192.168.179.89:2345` and I try to connect to it from the host it just gives me a timeout response on the host side. I ran tcpdump on the tap interface that was setup and I can see a bunch of SYN-ACK packets being exchanged. I'm pretty sure I have to set some Iptable rules in order to make this work and was wondering if you had any insight into it regarding this or the kind of firewall rules I need to setup in order to make this work or things I can do to debug this.

**Comment by ddcc** [comment]
Are you manually configuring the network instead of using the autogenerated run.sh script? Instead of binding gdbserver to a specific IP, I think you can just do `gdbserver :12345 foo`. Sometimes the networking can be a bit finicky where one host can't seem to talk to the other reliably, in which case you can try reversing the client/server using netcat, socat, or ssh (e.g. dropbear) using port forwarding.

**Comment by prashast** [comment]
Thanks for being so receptive, I truly appreciate it. I tried a couple of the alternatives but I keep stumbling across this error that whenever I tried to connect to the statically linked gdbserver from the host whether it be a tcp connection or through ssh port forwarding.
```
Ignoring packet error, continuing...
warning: unrecognized item "timeout" in "qSupported" response
Ignoring packet error, continuing...
```
My connection between the host and the guest seems to be setup correctly because I am able to ping the guest from the host and vice versa.  I was using gdb-7.10 and was wondering if that could be the issue since I am using a 2.6.32 kernel. Would using a deprecated version of GDB work or is there something else that might be going wrong. The gdbserver binary itself seemed to have no issues when I tested it on the host but it only has issues when I'm trying to connect to it from the host. Again, thanks for answering all these queries.

**Comment by ddcc** [comment]
If you're on Debian/Ubuntu, make sure you've installed `gdb-multiarch`. Depending on the mode that you launched gdbserver with, to connect to it in gdb you'll need to use either `target remote` or `target extended-remote`.

**Comment by prashast** [comment]
I tried connecting with both `gdb-mutliarch` and the `mipsel-unknown-linux-uclibc-gdb` and was using the appropriate modes on both sides, --multi with target extended-remote or target remote if my gdbserver was attached to a program but still the same error was cropping up.

**Comment by ddcc** [comment]
Is this over a serial link? It seems like some other people encountered this when they didn't configure the serial port and baudrate correctly. Otherwise, I can only suggest looking at it with wireshark and seeing if that's useful.

**Comment by prashast** [comment]
I finally managed to connect to the remote gdbserver when I used a newer kernel. For some reason the gdbserver wasn't working on the 2.6 kernel. However, now I'm facing this issue where whenever I chroot ,attach the webserver binary to the gdbserver and then when I try to connect `gdb-multiarch` using the commands: 
```
set arch mips
set endian little
set sysroot squashfs-root/  #my firmware root directory
target remote 192.168.179.89:2345
```
It gives me this error:

> Error while reading shared library symbols for squashfs-root/lib/ld-uClibc.so.0:
> Remote connection closed
> /build/gdb-cXfXJ3/gdb-7.11.1/gdb/thread.c:89: internal-error: inferior_thread: Assertion `tp' failed.

I even tried the gdb which comes with the cross compiler with which I had statically compiled my gdbserver with and I get the same issue. The `ld-uClibc.so.0` is a symbolic link to `ld-uClibc-0.9.28.so` though I doubt that would be an issue. I've set up a bind mount of the /proc inside the chroot because gdb complained that it wasn't able to read the proc entry of the pid that was created for the server.

> Reading symbols from target:/lib/ld-uClibc.so.0...(no debugging symbols found)...done.
> Error while reading shared library symbols for target:/lib/ld-uClibc.so.0:
> Remote connection closed

I tried to connect IDA to the gdbserver stub which works fine and attaches to the process successfully as long as I don't set a breakpoint. Without setting a breakpoint if I keep on continuing the process remotely it runs to it's completion, however as soon as i set a breakpoint, it breaks at that point but as soon as i resume it exits and the gdbserver segfaults with the error.

> linux_wait_1: Assertion `target_options & TARGET_WNOHANG' failed. 

I was wondering if there is anything that I'm doing wrong over here that you could point it out to me or a way that I can proceed to debug this issue.

**Comment by ddcc** [comment]
I'm a little confused about your setup. If you're using the remote gdbserver, then presumably the whole firmware is running in system-mode QEMU, so why is there a local chroot involved? You do need an extracted local copy of the firmware filesystem for GDB, but I believe setting the sysroot in GDB should take care of redirecting absolute paths into that. Are you sure the extracted ld-uClibc.so.0 file is valid ELF file and matches the one inside the QEMU image? I don't think I've seen either error before, I can only suggest trying again with the same version of gdb and gdbserver. You could also turn on verbose/debugging for both gdb and gdbserver to see if there's anything useful.

**Comment by prashast** [comment]
Yeah, I managed to get it to run using IDA, thanks for all the help!

**Comment by wjaxx** [comment]
> I finally managed to connect to the remote gdbserver when I used a newer kernel. For some reason the gdbserver wasn't working on the 2.6 kernel. However, now I'm facing this issue where whenever I chroot ,attach the webserver binary to the gdbserver and then when I try to connect `gdb-multiarch` using the commands:
> 
> ```
> set arch mips
> set endian little
> set sysroot squashfs-root/  #my firmware root directory
> target remote 192.168.179.89:2345
> ```
> It gives me this error:
> 
> > Error while reading shared library symbols for squashfs-root/lib/ld-uClibc.so.0:
> > Remote connection closed
> > /build/gdb-cXfXJ3/gdb-7.11.1/gdb/thread.c:89: internal-error: inferior_thread: Assertion `tp' failed.
> 
> I even tried the gdb which comes with the cross compiler with which I had statically compiled my gdbserver with and I get the same issue. The `ld-uClibc.so.0` is a symbolic link to `ld-uClibc-0.9.28.so` though I doubt that would be an issue. I've set up a bind mount of the /proc inside the chroot because gdb complained that it wasn't able to read the proc entry of the pid that was created for the server.
> 
> > Reading symbols from target:/lib/ld-uClibc.so.0...(no debugging symbols found)...done.
> > Error while reading shared library symbols for target:/lib/ld-uClibc.so.0:
> > Remote connection closed
> 
> I tried to connect IDA to the gdbserver stub which works fine and attaches to the process successfully as long as I don't set a breakpoint. Without setting a breakpoint if I keep on continuing the process remotely it runs to it's completion, however as soon as i set a breakpoint, it breaks at that point but as soon as i resume it exits and the gdbserver segfaults with the error.
> 
> > linux_wait_1: Assertion `target_options & TARGET_WNOHANG' failed.
> 
> I was wondering if there is anything that I'm doing wrong over here that you could point it out to me or a way that I can proceed to debug this issue. I have no idea why it would have an issue reading symbols from the shared library, I even tried to set the sysroot to the target using `set sysroot target:/` so that I can download the shared library and read the symbols from there but still the same issue kept coming up. The binary which I'm debugging is a mips lsb 32 bit executable.

I have the same issues that gdbserver cannot work in 2.6.x kernel.But I don't know how to change kernel in firmadye.Could you please give me a solution to get new kernel which firmadyne could support.
Thanks in advance.

**Comment by ddcc** [comment]
I don't think there's a straightforward solution. You'll need to rebase the firmadyne patches from e.g. the 2.6.x kernel onto e.g. a new Linux stable kernel, update the kernel configuration, and build the new kernel.

**Comment by sssyyynnngithub** [comment]
@ddcc prashast I want to use the gdbserver on the target ,so  I use the kernel vmlinux-3.2.0-4-4kc-malta instead. But  firmadyne can not infer network ip :
root@kali:~/firmadyne# ./scripts/inferNetwork.sh 1
Querying database for architecture... Password for user firmadyne: 
mipseb
Running firmware 1: terminating after 60 secs...
qemu-system-mips: -net nic,vlan=0: 'vlan' is deprecated. Please use 'netdev' instead.
qemu-system-mips: terminating on signal 2 from pid 1945 (timeout)
Inferring network...
Interfaces: []
Done!
and can not start network :
qemu-system-mips: -net nic,vlan=0: 'vlan' is deprecated. Please use 'netdev' instead.
[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Linux version 3.2.0-4-4kc-malta (debian-kernel@lists.debian.org) (gcc version 4.6.3 (Debian 4.6.3-14) ) #1 Debian 3.2.51-1
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU revision is: 00019300 (MIPS 24Kc)
[    0.000000] FPU revision is: 00739300
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 00001000 @ 00000000 (reserved)
[    0.000000]  memory: 000ef000 @ 00001000 (ROM data)
[    0.000000]  memory: 0067b000 @ 000f0000 (reserved)
[    0.000000]  memory: 0f894000 @ 0076b000 (usable)
[    0.000000] debug: ignoring loglevel setting.
[    0.000000] Wasting 60768 bytes for tracking 1899 unused pages
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Zone PFN ranges:
[    0.000000]   DMA      0x00000000 -> 0x00001000
[    0.000000]   Normal   0x00001000 -> 0x0000ffff
[    0.000000] Movable zone start PFN for each node
[    0.000000] early_node_map[1] active PFN ranges
[    0.000000]     0: 0x00000000 -> 0x0000ffff
[    0.000000] On node 0 totalpages: 65535
[    0.000000] free_area_init_node: node 0, pgdat 806bfd60, node_mem_map 81000000
[    0.000000]   DMA zone: 32 pages used for memmap
[    0.000000]   DMA zone: 0 pages reserved
[    0.000000]   DMA zone: 4064 pages, LIFO batch:0
[    0.000000]   Normal zone: 480 pages used for memmap
[    0.000000]   Normal zone: 60959 pages, LIFO batch:15
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 65023
[    0.000000] Kernel command line: root=/dev/sda1 console=ttyS0 nandsim.parts=64,64,64,64,64,64,64,64,64,64 rdinit=/firmadyne/preInit.sh rw debug ignore_loglevel print-fatal-signals=1 user_debug=31 firmadyne.syscall=0
[    0.000000] PID hash table entries: 1024 (order: 0, 4096 bytes)
[    0.000000] Dentry cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Inode-cache hash table entries: 16384 (order: 4, 65536 bytes)
[    0.000000] Primary instruction cache 2kB, VIPT, 2-way, linesize 16 bytes.
[    0.000000] Primary data cache 2kB, 2-way, VIPT, no aliases, linesize 16 bytes
[    0.000000] Writing ErrCtl register=00000000
[    0.000000] Readback ErrCtl register=00000000
[    0.000000] Memory: 252252k/254544k available (4614k kernel code, 2292k reserved, 1283k data, 220k init, 0k highmem)
[    0.000000] NR_IRQS:256
[    0.000000] CPU frequency 200.00 MHz
[    0.000000] Console: colour dummy device 80x25
[    0.000000] Calibrating delay loop... 1087.48 BogoMIPS (lpj=2174976)
[    0.020000] pid_max: default: 32768 minimum: 301
[    0.020000] Security Framework initialized
[    0.024000] AppArmor: AppArmor disabled by boot time parameter
[    0.024000] Mount-cache hash table entries: 512
[    0.028000] Initializing cgroup subsys cpuacct
[    0.028000] Initializing cgroup subsys memory
[    0.028000] Initializing cgroup subsys devices
[    0.028000] Initializing cgroup subsys freezer
[    0.028000] Initializing cgroup subsys net_cls
[    0.028000] Initializing cgroup subsys blkio
[    0.032000] Initializing cgroup subsys perf_event
[    0.040000] devtmpfs: initialized
[    0.048000] print_constraints: dummy: 
[    0.048000] NET: Registered protocol family 16
[    0.056000] bio: create slab <bio-0> at 0
[    0.060000] vgaarb: loaded
[    0.060000] SCSI subsystem initialized
[    0.060000] libata version 3.00 loaded.
[    0.064000] pci 0000:00:00.0: [11ab:4620] type 0 class 0x000600
[    0.064000] pci 0000:00:00.0: reg 14: [mem 0x01000000-0x01ffffff pref]
[    0.064000] pci 0000:00:0a.0: [8086:7110] type 0 class 0x000601
[    0.064000] pci 0000:00:0a.1: [8086:7111] type 0 class 0x000101
[    0.064000] pci 0000:00:0a.1: reg 20: [io  0x0000-0x000f]
[    0.064000] pci 0000:00:0a.2: [8086:7112] type 0 class 0x000c03
[    0.064000] pci 0000:00:0a.2: reg 20: [io  0x0000-0x001f]
[    0.064000] pci 0000:00:0a.3: [8086:7113] type 0 class 0x000680
[    0.064000] pci 0000:00:0a.3: address space collision: [io  0x1100-0x110f] conflicts with GT-64120 PCI I/O [io  0x1000-0x1fffff]
[    0.068000] pci 0000:00:0b.0: [1022:2000] type 0 class 0x000200
[    0.068000] pci 0000:00:0b.0: reg 10: [io  0x0000-0x001f]
[    0.068000] pci 0000:00:0b.0: reg 14: [mem 0x00000000-0x0000001f]
[    0.068000] pci 0000:00:0b.0: reg 30: [mem 0x00000000-0x0003ffff pref]
[    0.068000] pci 0000:00:12.0: [1022:2000] type 0 class 0x000200
[    0.068000] pci 0000:00:12.0: reg 10: [io  0x0000-0x001f]
[    0.068000] pci 0000:00:12.0: reg 14: [mem 0x00000000-0x0000001f]
[    0.068000] pci 0000:00:12.0: reg 30: [mem 0x00000000-0x0003ffff pref]
[    0.068000] pci 0000:00:13.0: [1022:2000] type 0 class 0x000200
[    0.068000] pci 0000:00:13.0: reg 10: [io  0x0000-0x001f]
[    0.068000] pci 0000:00:13.0: reg 14: [mem 0x00000000-0x0000001f]
[    0.068000] pci 0000:00:13.0: reg 30: [mem 0x00000000-0x0003ffff pref]
[    0.068000] pci 0000:00:14.0: [1022:2000] type 0 class 0x000200
[    0.068000] pci 0000:00:14.0: reg 10: [io  0x0000-0x001f]
[    0.068000] pci 0000:00:14.0: reg 14: [mem 0x00000000-0x0000001f]
[    0.068000] pci 0000:00:14.0: reg 30: [mem 0x00000000-0x0003ffff pref]
[    0.068000] pci 0000:00:15.0: [1013:00b8] type 0 class 0x000300
[    0.068000] pci 0000:00:15.0: reg 10: [mem 0x00000000-0x01ffffff pref]
[    0.068000] pci 0000:00:15.0: reg 14: [mem 0x00000000-0x00000fff]
[    0.068000] pci 0000:00:15.0: reg 30: [mem 0x00000000-0x0000ffff pref]
[    0.072000] vgaarb: device added: PCI:0000:00:15.0,decodes=io+mem,owns=none,locks=none
[    0.072000] pci 0000:00:0a.3: BAR 14: [io  0x1100-0x110f] has bogus alignment
[    0.072000] pci 0000:00:15.0: BAR 0: assigned [mem 0x10000000-0x11ffffff pref]
[    0.072000] pci 0000:00:0b.0: BAR 6: assigned [mem 0x12000000-0x1203ffff pref]
[    0.072000] pci 0000:00:12.0: BAR 6: assigned [mem 0x12040000-0x1207ffff pref]
[    0.076000] pci 0000:00:13.0: BAR 6: assigned [mem 0x12080000-0x120bffff pref]
[    0.076000] pci 0000:00:14.0: BAR 6: assigned [mem 0x120c0000-0x120fffff pref]
[    0.076000] pci 0000:00:15.0: BAR 6: assigned [mem 0x12100000-0x1210ffff pref]
[    0.076000] pci 0000:00:15.0: BAR 1: assigned [mem 0x12110000-0x12110fff]
[    0.076000] pci 0000:00:0a.2: BAR 4: assigned [io  0x1000-0x101f]
[    0.076000] pci 0000:00:0b.0: BAR 0: assigned [io  0x1020-0x103f]
[    0.076000] pci 0000:00:0b.0: BAR 1: assigned [mem 0x12111000-0x1211101f]
[    0.076000] pci 0000:00:12.0: BAR 0: assigned [io  0x1040-0x105f]
[    0.080000] pci 0000:00:12.0: BAR 1: assigned [mem 0x12111020-0x1211103f]
[    0.080000] pci 0000:00:13.0: BAR 0: assigned [io  0x1060-0x107f]
[    0.084000] pci 0000:00:13.0: BAR 1: assigned [mem 0x12111040-0x1211105f]
[    0.084000] pci 0000:00:14.0: BAR 0: assigned [io  0x1080-0x109f]
[    0.084000] pci 0000:00:14.0: BAR 1: assigned [mem 0x12111060-0x1211107f]
[    0.084000] pci 0000:00:0a.1: BAR 4: assigned [io  0x10a0-0x10af]
[    0.088000] Switching to clocksource MIPS
[    0.124000] NET: Registered protocol family 2
[    0.124000] IP route cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.128000] TCP established hash table entries: 8192 (order: 4, 65536 bytes)
[    0.128000] TCP bind hash table entries: 8192 (order: 3, 32768 bytes)
[    0.128000] TCP: Hash tables configured (established 8192 bind 8192)
[    0.128000] TCP reno registered
[    0.128000] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.128000] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.132000] NET: Registered protocol family 1
[    0.132000] RPC: Registered named UNIX socket transport module.
[    0.132000] RPC: Registered udp transport module.
[    0.132000] RPC: Registered tcp transport module.
[    0.132000] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.136000] PCI: Enabling device 0000:00:0a.2 (0000 -> 0001)
[    0.136000] PCI: CLS 0 bytes, default 64
[    0.144000] audit: initializing netlink socket (disabled)
[    0.144000] type=2000 audit(1571916629.144:1): initialized
[    0.144000] VFS: Disk quotas dquot_6.5.2
[    0.148000] Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.148000] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.148000] msgmni has been set to 492
[    0.156000] alg: No test for stdrng (krng)
[    0.160000] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 253)
[    0.160000] io scheduler noop registered
[    0.160000] io scheduler deadline registered
[    0.160000] io scheduler cfq registered (default)
[    0.160000] PCI: Enabling device 0000:00:15.0 (0000 -> 0002)
[    0.164000] cirrusfb 0000:00:15.0: Cirrus Logic chipset on PCI bus, RAM (4096 kB) at 0x10000000
[    0.368000] Console: switching to colour frame buffer device 80x30
[    0.392000] Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled
[    0.416000] serial8250.0: ttyS0 at I/O 0x3f8 (irq = 4) is a 16550A
[    0.416000] console [ttyS0] enabled, bootconsole disabled
[    0.416000] console [ttyS0] enabled, bootconsole disabled
[    0.436000] serial8250.0: ttyS1 at I/O 0x2f8 (irq = 3) is a 16550A
[    0.440000] ata_piix 0000:00:0a.1: version 2.13
[    0.440000] PCI: Enabling device 0000:00:0a.1 (0000 -> 0001)
[    0.444000] PCI: Setting latency timer of device 0000:00:0a.1 to 64
[    0.448000] scsi0 : ata_piix
[    0.448000] scsi1 : ata_piix
[    0.448000] ata1: PATA max UDMA/33 cmd 0x1f0 ctl 0x3f6 bmdma 0x10a0 irq 14
[    0.448000] ata2: PATA max UDMA/33 cmd 0x170 ctl 0x376 bmdma 0x10a8 irq 15
[    0.452000] pcnet32: pcnet32.c:v1.35 21.Apr.2008 tsbogend@alpha.franken.de
[    0.452000] PCI: Enabling device 0000:00:0b.0 (0000 -> 0003)
[    0.452000] PCI: Setting latency timer of device 0000:00:0b.0 to 64
[    0.460000] pcnet32: PCnet/PCI II 79C970A at 0x1020, 52:54:00:12:34:56 assigned IRQ 10
[    0.460000] pcnet32: eth0: registered as PCnet/PCI II 79C970A
[    0.464000] PCI: Enabling device 0000:00:12.0 (0000 -> 0003)
[    0.464000] PCI: Setting latency timer of device 0000:00:12.0 to 64
[    0.464000] pcnet32: PCnet/PCI II 79C970A at 0x1040, 52:54:00:12:34:57 assigned IRQ 10
[    0.464000] pcnet32: eth1: registered as PCnet/PCI II 79C970A
[    0.464000] PCI: Enabling device 0000:00:13.0 (0000 -> 0003)
[    0.464000] PCI: Setting latency timer of device 0000:00:13.0 to 64
[    0.468000] pcnet32: PCnet/PCI II 79C970A at 0x1060, 52:54:00:12:34:58 assigned IRQ 10
[    0.468000] pcnet32: eth2: registered as PCnet/PCI II 79C970A
[    0.468000] PCI: Enabling device 0000:00:14.0 (0000 -> 0003)
[    0.472000] PCI: Setting latency timer of device 0000:00:14.0 to 64
[    0.472000] pcnet32: PCnet/PCI II 79C970A at 0x1080, 52:54:00:12:34:59 assigned IRQ 11
[    0.472000] pcnet32: eth3: registered as PCnet/PCI II 79C970A
[    0.472000] pcnet32: 4 cards_found
[    0.476000] serio: i8042 KBD port at 0x60,0x64 irq 1
[    0.476000] serio: i8042 AUX port at 0x60,0x64 irq 12
[    0.476000] mousedev: PS/2 mouse device common for all mice
[    0.476000] rtc_cmos rtc_cmos: rtc core: registered rtc_cmos as rtc0
[    0.476000] rtc0: alarms up to one day, 242 bytes nvram
[    0.476000] TCP cubic registered
[    0.484000] NET: Registered protocol family 17
[    0.484000] Registering the dns_resolver key type
[    0.484000] PM: Hibernation image not present or could not be loaded.
[    0.488000] registered taskstats version 1
[    0.488000] rtc_cmos rtc_cmos: setting system clock to 2019-10-24 11:30:31 UTC (1571916631)
[    0.488000] Initializing network drop monitor service
[    0.600000] input: AT Raw Set 2 keyboard as /devices/platform/i8042/serio0/input/input0
[    0.628000] ata1.01: NODEV after polling detection
[    0.628000] ata2.01: NODEV after polling detection
[    0.632000] ata1.00: ATA-7: QEMU HARDDISK, 2.5+, max UDMA/100
[    0.636000] ata1.00: 2097152 sectors, multi 16: LBA48 
[    0.640000] ata2.00: ATAPI: QEMU DVD-ROM, 2.5+, max UDMA/100
[    0.640000] ata2.00: configured for UDMA/33
[    0.644000] ata1.00: configured for UDMA/33
[    0.660000] scsi 0:0:0:0: Direct-Access     ATA      QEMU HARDDISK    2.5+ PQ: 0 ANSI: 5
[    0.668000] sd 0:0:0:0: [sda] 2097152 512-byte logical blocks: (1.07 GB/1.00 GiB)
[    0.672000] sd 0:0:0:0: [sda] Write Protect is off
[    0.672000] sd 0:0:0:0: [sda] Mode Sense: 00 3a 00 00
[    0.676000] scsi 1:0:0:0: CD-ROM            QEMU     QEMU DVD-ROM     2.5+ PQ: 0 ANSI: 5
[    0.680000] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    0.696000]  sda: sda1
[    0.700000] sd 0:0:0:0: [sda] Attached SCSI disk
[    0.704000] EXT4-fs (sda1): couldn't mount as ext3 due to feature incompatibilities
[    0.708000] EXT4-fs (sda1): mounting ext2 file system using the ext4 subsystem
[    0.716000] EXT4-fs (sda1): warning: mounting unchecked fs, running e2fsck is recommended
[    0.716000] EXT4-fs (sda1): mounted filesystem without journal. Opts: (null)
[    0.720000] VFS: Mounted root (ext2 filesystem) on device 8:1.
[    0.720000] Freeing prom memory: 956k freed
[    0.724000] Freeing unused kernel memory: 220k freed

Mounting etc to ramfs.      [DONE]

Mounting var to jffs2.      [FAILED]

Checking SSH keys.          [DONE]

Checking for run file.      [DONE]

Starting System Logger.     [DONE]

Starting Kernel Logger.     [DONE]
[    4.864000] klogd/92: potentially unexpected fatal signal 10.
[    4.864000] 
[    4.864000] Cpu 0
[    4.864000] $ 0   : 00000000 1000a400 00000008 ffffffff
[    4.864000] $ 4   : 00000000 00000000 00000000 7fbcae80
[    4.864000] $ 8   : 00000000 00000000 00000000 7fbcaca8
[    4.864000] $12   : 77b53868 77b66004 92492493 00000044
[    4.864000] $16   : 7fbcade8 ffffffff 7fbcb4f8 7fbcb4f8
[    4.864000] $20   : 7fbcb49b 77b66c40 7fbcaee0 00000000
[    4.864000] $24   : 00000000 77b3cbc0                  
[    4.868000] $28   : 77b6e440 7fbcacf8 ffffffff 77b395c8
[    4.868000] Hi    : 00000001
[    4.868000] Lo    : 00000000
[    4.868000] epc   : 77b39648 0x77b39648
[    4.868000]     Not tainted
[    4.868000] ra    : 77b395c8 0x77b395c8
[    4.868000] Status: 0000a413    USER EXL IE 
[    4.868000] Cause : 00800010
[    4.868000] BadVA : ffffffff
[    4.868000] PrId  : 00019300 (MIPS 24Kc)

Starting Panel LED.         [    5.984000] panel_led_driver: module_layout: kernel tainted.
[    5.984000] Disabling lock debugging due to kernel taint
[    5.984000] panel_led_driver: version magic '2.6.23-WNAP320_V2.0.3 mod_unload MIPS32_R2 32BIT ' should be '3.2.0-4-4kc-malta mod_unload modversions MIPS32_R1 32BIT '
insmod: cannot insert '/lib/modules/panel-led/panel-led-driver.ko': invalid module format
[FAILED]

Starting watchdog.          Error in opening the device.
: No such device
[    6.084000] sys_watchdog: version magic '2.6.23-WNAP320_V2.0.3 mod_unload MIPS32_R2 32BIT ' should be '3.2.0-4-4kc-malta mod_unload modversions MIPS32_R1 32BIT '
insmod: cannot insert '/lib/modules/sys-watchdog/sys-watchdog.ko': invalid module format
[FAILED]
Error in opening the device
: No such device

Starting Reset Detect.      [    6.156000] panel_reset_sw: version magic '2.6.23-WNAP320_V2.0.3 mod_unload MIPS32_R2 32BIT ' should be '3.2.0-4-4kc-malta mod_unload modversions MIPS32_R1 32BIT '
insmod: cannot insert '/lib/modules/panel-reset-sw/panel-reset-sw.ko': invalid module format
[FAILED]
WN802T_SYS_RESET_DETECT_IOC returned err 

Checking Manufac. data      [DONE]

Checking board file.        [CREATED]

Loading Ethernet module.    [    8.424000] ag7100_mod: version magic '2.6.23-WNAP320_V2.0.3 mod_unload MIPS32_R2 32BIT ' should be '3.2.0-4-4kc-malta mod_unload modversions MIPS32_R1 32BIT '
insmod: cannot insert '/lib/modules/ethernet/ag7100_mod.ko': invalid module format
[FAILED]

Checking database.          [DONE]

Verifing checksum.          [DONE]

Loading Bridge module.      [   10.660000] llc: version magic '2.6.23-WNAP320_V2.0.3 mod_unload MIPS32_R2 32BIT ' should be '3.2.0-4-4kc-malta mod_unload modversions MIPS32_R1 32BIT '
insmod: cannot insert '/lib/modules/net/llc/llc.ko': invalid module format
[FAILED]

Loading wlan modules.       [   11.920000] ath_hal: version magic '2.6.23-WNAP320_V2.0.3 mod_unload MIPS32_R2 32BIT ' should be '3.2.0-4-4kc-malta mod_unload modversions MIPS32_R1 32BIT '
insmod: cannot insert '/lib/modules/wlan/ath_hal.ko': invalid module format
[FAILED]

Creating vap interface.     /usr/local/bin/wlanconfig: ioctl: No such device
ifconfig: SIOCSIFTXQLEN: No such device
/usr/local/bin/wlanconfig: ioctl: No such device
ifconfig: SIOCSIFTXQLEN: No such device
/usr/local/bin/wlanconfig: ioctl: No such device
ifconfig: SIOCSIFTXQLEN: No such device
/usr/local/bin/wlanconfig: ioctl: No such device
ifconfig: SIOCSIFTXQLEN: No such device
/usr/local/bin/wlanconfig: ioctl: No such device
ifconfig: SIOCSIFTXQLEN: No such device
/usr/local/bin/wlanconfig: ioctl: No such device
ifconfig: SIOCSIFTXQLEN: No such device
/usr/local/bin/wlanconfig: ioctl: No such device
ifconfig: SIOCSIFTXQLEN: No such device
/usr/local/bin/wlanconfig: ioctl: No such device
ifconfig: SIOCSIFTXQLEN: No such device
[DONE]

Creating wds interface.     /usr/local/bin/wlanconfig: ioctl: No such device
ifconfig: SIOCSIFMTU: No such device
/usr/local/bin/wlanconfig: ioctl: No such device
ifconfig: SIOCSIFMTU: No such device
/usr/local/bin/wlanconfig: ioctl: No such device
ifconfig: SIOCSIFMTU: No such device
/usr/local/bin/wlanconfig: ioctl: No such device
ifconfig: SIOCSIFMTU: No such device
[DONE]

Starting configd.           [DONE]

Starting web server.        [DONE]

Starting Translator...      start-stop-daemon: cannot start /usr/bin/log_ro: No such file or directory
[syslog]

Starting Translator...      [password]

Starting Translator...      [ssh]

Starting Translator...      [snmp]

Starting Translator...      [telnet]

Starting Translator...      [dns]

Starting Translator...      add bridge failed: Package not installed
set forward delay failed: No such device
ifconfig: SIOCGIFFLAGS: No such device
set stp status failed: No such device
interface eth0 does not exist!
[   21.068000] pcnet32 0000:00:0b.0: eth0: link up
set cascaded bridge failed: No such device
ifconfig: SIOCSIFADDR: No such device
route: SIOCADDRT: No such device
[bridge_and_vlan_translator]

Starting Translator...      [   21.740000] hostapd_tr/533: potentially unexpected fatal signal 11.
[   21.740000] 
[   21.740000] Cpu 0
[   21.740000] $ 0   : 00000000 1000a400 00000004 00000000
[   21.740000] $ 4   : 00000004 00419f18 00000000 00000001
[   21.740000] $ 8   : 77000004 00a9b0b8 00000031 fffffff0
[   21.740000] $12   : 80000000 00000234 81000000 76fb4578
[   21.740000] $16   : 7ffa8d0c 7ffa8ba0 7fe19554 ffffffff
[   21.744000] $20   : 7ffa8c64 00401834 00000001 004019f0
[   21.744000] $24   : 00000002 76fd77d0                  
[   21.744000] $28   : 00435880 7ffa85f8 7ffa85f8 00416804
[   21.744000] Hi    : 00000005
[   21.744000] Lo    : 19999999
[   21.744000] epc   : 76fd77d0 0x76fd77d0
[   21.744000]     Tainted: GF           
[   21.744000] ra    : 00416804 0x416804
[   21.744000] Status: 0000a413    USER EXL IE 
[   21.744000] Cause : 00800008
[   21.744000] BadVA : 00000004
[   21.744000] PrId  : 00019300 (MIPS 24Kc)
Segmentation fault
[hostapd_tr]

Starting Translator...      [nmbd_tr]

Starting Translator...      sh: cannot create /proc/sys/net/bridge/bridge-http-redirect-flush-mac: nonexistent directory
sh: cannot create /proc/sys/net/bridge/bridge-http-redirect-enabled: nonexistent directory
[http_redirect_tr]

Starting Translator...      [dhcp]

Starting Translator...      kill: cannot kill pid 611: No such process
[ntp]

Starting Translator...      [timezone]

Starting Translator...      kill: cannot kill pid 624: No such process
[sc_radio]
Error in opening the device.
: No such device

System initilization is ..  [DONE...]


Welcome to SDK.

Have a lot of fun...

netgear123456 login: 
Could you help me ?Thank you !

**Comment by sssyyynnngithub** [comment]
@ddcc Sir ,Could you give me the instructions on how to rebase the firmadyne patches from 2.6.x kernel noto a new linux stable kernel , update the kernel configuration, and build the new kernel . Thank you very much !

**Comment by sssyyynnngithub** [comment]
@prashast . Sir , do you solve the problem of using IDA to debug on firmadyne? Could you please share how do you do it ? Thank you very much !
